### PR TITLE
site-packages/pip.py: Improve readability of BUNDLED_MODULES

### PR DESCRIPTION
**Pull request by cclauss**
@yjqiang Your review please?

### CODE REVIEW

**Comment by yjqiang** [comment]
Maybe I should fix things like `bs4` and `beautifulsoup4`? I think we should just keep `beautifulsoup4` which is the package name installed in pyto, not bs4?

**Comment by yjqiang** [comment]
I mean if you try to install bs4 (not beautifulsoup4) in pyto by using pip, you can find that you can’t make it. I don’t think it is necessary.

**Comment by cclauss** [comment]
Do we need PIL?
Do we need Pillow and pillow?
Do we need queue?

**Comment by yjqiang** [comment]
> Do we need PIL?
> Do we need _both_ Pillow _and_ pillow?
> Do we need queue?

1. I don’t think we should need PIL.
2. pillow and Pillow means the same thing for pypi. 
3.

**Comment by yjqiang** [comment]
> Do we need PIL?
> Do we need _both_ Pillow _and_ pillow?
> Do we need queue?

So what is your answer?

**Comment by ColdGrub1384** [comment]
Thanks. `queue` is not needed, I don't know why I put it there

**Pull request merged**
